#!/bin/bash -e

JULIA_PROJECT="/home/jovyan"
julia -e "import Pkg; Pkg.instantiate(); Pkg.status(); Pkg.precompile()"

jupyter serverextension enable --sys-prefix jupyter_server_proxy
jupyter labextension install @jupyterlab/server-proxy
jupyter lab build