#!/bin/bash -e

JULIA_PROJECT="/home/jovyan"
julia -e "import Pkg; Pkg.Registry.update(); Pkg.instantiate(); Pkg.status(); Pkg.precompile()"

jupyter labextension install @jupyterlab/server-proxy
jupyter lab build
jupyter lab clean
pip install . --no-cache-dir
rm -rf ~/.cache
